### ISSUE TITLE
Improve exaslct starter script to mount all path which are used by the command line parameter

### ISSUE THREAD

**Issue by tkilias** [exasol/script-languages-container-tool#10]
## Background
- Currently, the exaslct starter script only mounts the current working directory, however the user can specify paths to other locations in certain command line parameters of exaslct, such as --flavor-path, --save-path, --export-path, --cache-directory, --temporary-base-directory, --output-directory, ...
- At the moment, the starter script would use paths inside the runner container for them, if they are not relative the current working directory, as such they are only available in the container and don't get synced to the host

## Acceptance Criteria
- path used in the command line parameters are get mounted into the runner container
- the permissions of these mounted directories get fixed after or during the run, because the container and the host might use different uids and gids

**Comment by tomuben** [comment]
Some of the paths are not given as parameters to the script (for example export). Maybe we should discuss another approach...

**Comment by tomuben** [comment]
@tkilias here a list of all parameters which exaslct accepts

| Parameter | Type | Default
| -------------- | ------ | --------- |
| --export-path | OutPath? ||
| --test-folder | InPath ||
| --test-file | InFileIn || 
| --save-directory | - OutPath ||
| --flavor-path | - InPath ||
| --task-dependencies-dot-file | OutFile ||
| --cache-directory | OutPath ||
| --temporary-base-directory | OutPath | /tmp |
| --output-directory | OutPath | /.build_output |

**Comment by tomuben** [comment]
The default values for --temporary-base-directory and --output-directory make things even more difficult, let's discuss again.

**Comment by tkilias** [comment]
| Parameter | Type | Default| Comment
| -------------- | ------ | --------- | ------------- |
| --export-path | OutPath |||
| --test-folder | InPath ||currently hardcoded to `tests/<parameter>`|
| --test-file | InFile || currently hardcoded to `tests/<parameter>`|
| --save-directory | OutPath |||
| --flavor-path | InPath |||
| --task-dependencies-dot-file | OutFile |||
| --cache-directory | InPath ||used in [image_load_task](https://github.com/exasol/integration-test-docker-environment/blob/19b409b8042d837f2e7e79c3e876ac9e35524a16/exasol_integration_test_docker_environment/lib/docker/images/create/docker_image_load_task.py)|
| --temporary-base-directory | OutPath | /tmp ||
| --output-directory | OutPath | /.build_output ||

**Comment by tkilias** [comment]
You are right the defaults make it a bit more complicated, but I think ./.build_output is automatically shared if we share $PWD. And, if we don't find --temporary-base-directory we need to add /tmp.

**Comment by tomuben** [comment]
Ok, I will start implementation then
