### ISSUE TITLE
Add GitHub Action on Mac to test the exaslct starter scripts in dry_run mode

### ISSUE THREAD

**Issue by tkilias** [exasol/script-languages-container-tool#107]
# Background:

- we can't test the whole system on Mac on Github Actions, because it doesn't support Docker, but we can test the starter_scripts in a dry_run mode in which we don't execute the docker command

# Acceptance Criteria
- implement dry run mode for starter scripts (Use Environment Variable as switch)
- Add Github Workflow to test the starter scripts and install scripts on Mac
- Fix exaslct for MacOsX

**Comment by redcatbear** [comment]
Shelving, because we don't want to spend the capacity to support Mac for the slct at the moment.
