### ISSUE TITLE
Use Virtualbox in Github Action on Mac to run Docker

### ISSUE THREAD

**Issue by tkilias** [exasol/script-languages-container-tool#108]
# Background:

- Github Actions can run VirtualBox
- You can configure docker such that it use the Docker daemon in this Virtual Machine for building and running container
- https://docs.docker.com/engine/security/protect-access/
- https://dockerlabs.collabnix.com/beginners/components/daemon/access-daemon-externally.html
- https://dhwaneetbhatt.com/blog/run-docker-without-docker-desktop-on-macos (uses vagrant) **<- try this first**

The following could be good for debugging the CI: https://github.com/marketplace/actions/debugging-with-ssh

**Comment by redcatbear** [comment]
No capacity for Mac support atm.
