### ISSUE TITLE
Replace the bash starter scripts with go starter bin

### ISSUE THREAD

**Issue by tkilias** [exasol/script-languages-container-tool#112]
# Background

- The bash starter scripts are maintenance nightmare 
- Using slim go starter binaries should avoid many of their problems and doesn't need any other dependencies

# Potential issues

- Different glibc can be a problem and when we interact with docker we probably need network, which use glibc, we need to test what is necessary to get the binaries running with different glibc

# Acceptance Criteria

- Write Go starter 
- Write tests
- Generate binaries for different OSs and platforms (x86)
  - maybe we can use the same what trivy uses https://github.com/aquasecurity/trivy/runs/5047987717?check_suite_focus=true
- Run tests on different OSs

**Comment by tomuben** [comment]
Obsolete because of #234.
