### ISSUE TITLE
Failed to follow the installation instructions

### ISSUE THREAD

**Issue by floriaso** [exasol/script-languages-container-tool#138]
Hi There

I tried to get to know the script-languages-container-tool but failed to follow the installation instructions. Specifically the second Step:

"Then you can use the Python package itself or install the starter scripts which allow to run exaslct within a docker image: exasol_script_languages_container_tool.main install-starter-scripts --install-path $YOUR_INSTALL_PATH"

Could you please elaborate on the two options? How to use the Python package itself? How to install the started scripts?

Thanks,
floriaso

**Comment by tkilias** [comment]
Hi @floriaso,

Thank you for your question. You have two options to use the container-tool. You can install it as Python package, then you can call use it via
```
python3 -m exasol_script_languages_container_tool.main <command> ...
```
You can either already use the command build, export, ... directly. 

Or, alternatively, you can install starter scripts. These starter scripts work standalone without the package installed. We use them in other GitHub Repositories, when we want to provide a CLI for users without them installing another Python. These starter scripts start a bootstrap Docker Container and run the container-tool inside the container.

For example, in the https://github.com/exasol/script-languages-release/ Repository we already installed the starter scripts and you only need to call `./exaslct ....` in the root of the Repository.

I hope this helps. Please let me know, when you have more questions.

**Comment by redcatbear** [comment]
@tkilias, do we need to update documentation (e.g. add a link to a user guide)? If not, I think you can close this ticket.

**Comment by tkilias** [comment]
@redcatbear I think, we should clarify this in the documentation a bit. I will create a follow-up ticket.
