### ISSUE TITLE
Inject import for DockerFlavorAnalyzeImageTask into build_steps.py

### ISSUE THREAD

**Issue by tkilias** [exasol/script-languages-container-tool#18]
Background:

- Currently, each build_steps.py has it own import statement for DockerFlavorAnalyzeImageTask 
- These import statement are fixed to one package path and one name
- This complicates changes to the structure in script-languages-container-tool, because if we change the module path or name of the class the flavors will break
- If we inject the import statement during the dynamic load of the build_steps.py file, we can implement compatibility mechanisms, for example we could change the name of the class with import, as follows 
```
from path.to.package import NewName as OldName
```
- With changes to the package path also only require a change in the injected import statement

**Comment by tomuben** [comment]
We changed the plans: It's better to get rid of build_steps.py completely:#87
