### ISSUE TITLE
Use host network for docker starter

### ISSUE THREAD

**Issue by tkilias** [exasol/script-languages-container-tool#26]
## Background

- In the docker starter exaslct_within_docker_container.sh, we start exaslct in a docker container
- If we use `exaslct upload ` customers probably assume most of the time the forwarded ports of the docker-db to be the ports to connect, too
- However, if you run in docker container and have it not on the host network the port forwards are inaccessible from inside the container
- To provide a more natural behavior we should start the docker starter container with `--network host`

**Comment by tomuben** [comment]
Pushed https://github.com/exasol/script-languages/tree/bug/%2326-docker-host-network
@tkilias , although this issue is under script-languages-container-tool i pushed the fix to script-languages. I guess we should move this issue there? (Or did I misunderstand something?)

**Comment by tkilias** [comment]
@tomuben The issue needs to be fixed in this repository, because the script-languages repository only contains an installation of the starter script. The reason is, that exaslct will be used in the future in other repositories, too, and we need a single source of truth.
